### ISSUE TITLE
 Authorization 관련

### ISSUE THREAD

**Issue by webhacking** [EncoredTech/enertalk-sample#11]
아래와 같은 주소로 비동기(ajax)로 요청한다했을 때,
`https://enertalk-auth.encoredtech.com/login?client_id=d29vcmFteW9vbkBnbWFpbC5jb21fSGVsbG9Xb3JsZA==&redirect_uri=http://codepen.io/wooramy/full/aNZymW/&response_type=code&app_version=web&back_url=/authorization`

access_token, refresh_token값등 을 받아올수있나요?

**Comment by wooramy** [comment]
안녕하세요, 질문 감사합니다. 아마 여기 있는 코드는 아니고 다음 코드펜에 있는 예제를 보고 이메일 주신 것이지요? 
http://codepen.io/wooramy/pen/aNZymW

질문 주신것처럼 요청을 보내시고 사용자의 동의를 거친 뒤에는 다음과 같은 url로 re-direct되게 됩니다.
http://codepen.io/wooramy/full/aNZymW/?code=xxx

xxx에 해당하는 부분에 authorization code 값을 받을 수 있고, 이를 이용해 access token, refresh token을 받으실 수 있습니다 :)

**Comment by webhacking** [comment]
안녕하세요.
답변감사드립니다.

re-direct 하는 url을 요청 호스트('http://enermate.hax0r.info/') 와 동일하게하면 될까요?
폼 데이터로 email,password값 같이 보냅니다.

사용자 동의 경우에는 어떤식으로 넘겨야할지.. 
아래와 답변을 참고해서 했습니다. 
- http://stackoverflow.com/questions/11440398/how-do-i-implement-secure-oauth2-consumption-in-javascript

**Comment by wooramy** [comment]
아 네 반환된 authorization code를 프로세스 할 수 있는 페이지로 redirect url을 보내시면 되는데요 (코드펜 예제의 경우 다시 코드펜으로 돌아오게 해두었구요.) http://developer.encoredtech.com/my-apps/ 페이지에 가셔서 redirect url 항목을 같은 값으로 업데이트 해주셔야 합니다. 

폼 데이터로 email, password를 보내신다고 하셨는데 아마 @webhacking 님의 개발자 계정 정보를 보내신것 같은데, 그게 아니고 @webhacking 님께서 필요한 건 개발자 계정이 아니라 에너톡 사용자 계정의 리소스이므로 예를 들어 https://enertalk-auth.encoredtech.com/login 페이지에 있는 입력 박스에 http://developer.encoredtech.com/testaccount/ 에 제공된 테스트 사용자 계정 id와 password를 입력하면 되세요~

**Comment by webhacking** [comment]
@wooramy 감사합니다.
